### ISSUE TITLE
Unable to recognize numbers

### ISSUE THREAD

**Issue by bdavs** [DanGarcia595/MovieGet#1]
![image](https://user-images.githubusercontent.com/11635713/28348158-52dd0288-6c09-11e7-8ead-a643cd17c871.png)

**Comment by bdavs** [comment]
I haven't tested this a lot, but it seems like its only for this case.

**Comment by bdavs** [comment]
#3  should fix this

**Comment by DanGarcia595** [comment]
Closed by #3
