### ISSUE TITLE
program continues without error when even no movie is found,

### ISSUE THREAD

**Issue by bdavs** [DanGarcia595/MovieGet#2]
![image](https://user-images.githubusercontent.com/11635713/28348439-0cb839ce-6c0b-11e7-8e9c-33e8a2b166d2.png)

When the search returns an xml page that does not have any results, the program continues as if completing without throwing a warning

![image](https://user-images.githubusercontent.com/11635713/28348429-fd1ae2b4-6c0a-11e7-810e-dc41a9d13534.png)

**Comment by bdavs** [comment]
#3 should also fix this

**Comment by DanGarcia595** [comment]
closed by #3
